eval_aishell-1:
  data:
    prompt: Transcribe the Chinese speech into text.
    data:
    - AISHELL-1/test/test_000{000..011}.tar.gz
    key: text
    repo_id: mispeech/xares_llm_data
  batch_size: 4
  num_workers: 0
  metric: iCER
