eval_clotho:
  data:
    data:
    - env/Clotho/test/test_00000{00..04}.tar.gz
    key: text;caption;captions;label;labels
    prompt: Generate a short caption for the audio.
  batch_size: 4
  num_workers: 0
  metric: FENSE
