eval_esc-50:
  data:
    data:
    - ESC-50/test/esc50_fold_5_0000000.tar.gz
    key: text;caption;captions;label;labels
    prompt: Classify the environmental sound.
    repo_id: mispeech/xares_llm_data
  batch_size: 128
  num_workers: 0
  metric: Accuracy
