eval_freemusicarchive:
  data:
    data:
    - FreeMusicArchive/test/fma_small_test_0000{00..07}.tar.gz
    key: genre
    prompt: Classify the music genre (FMA).
    repo_id: mispeech/xares_llm_data
  batch_size: 8
  num_workers: 0
  metric: Accuracy
