eval_mecat:
  data:
    data:
    - 000/test_0000-0000000.tar.gz
    - 0M0/test_0000-0000000.tar.gz
    - SMA/test_0000-0000000.tar.gz
    - S00/test_0000-0000000.tar.gz
    - 0MA/test_0000-0000000.tar.gz
    - S0A/test_0000-0000000.tar.gz
    - SM0/test_0000-0000000.tar.gz
    - 00A/test_0000-0000000.tar.gz
    key: long
    prompt: Write a general audiocaption.
    repo_id: mispeech/MECAT-Caption
  batch_size: 4
  num_workers: 0
  metric: DATE
