eval_nsynth:
  data:
    data:
    - NSynth/test/test_0000000.tar.gz
    key: text;caption;captions;label;labels
    prompt: Classify the music instrument.
    repo_id: mispeech/xares_llm_data
  batch_size: 16
  num_workers: 0
  metric: Accuracy
