eval_aishell-1:
  prompt: Transcribe the Chinese speech into text.
  key: text
  data:
  - env/AISHELL-1/test/test_0000{000..011}.tar.gz
  batch_size: 4
  num_workers: 0
  metric: iCER
eval_asvspoof2015:
  prompt: Detect if the audio is genuine or a spoof.
  key: text;caption;captions;label;labels
  data:
  - env/ASVSpoof2015/test/asvspoof_eval_000{00..193}.tar.gz
  batch_size: 4
  num_workers: 0
  metric: Accuracy
eval_clotho:
  prompt: Generate a short caption for the audio.
  key: text;caption;captions;label;labels
  data:
  - env/Clotho/test/test_00000{00..04}.tar.gz
  batch_size: 4
  num_workers: 0
  metric: FENSE
eval_esc-50:
  prompt: Classify the environmental sound.
  key: text;caption;captions;label;labels
  data:
  - env/ESC-50/test/esc50_fold_5_0000000.tar.gz
  batch_size: 4
  num_workers: 0
  metric: Accuracy
eval_fluentspeechcommands:
  prompt: Identify the command, action, and object from the speech.
  key: text;caption;captions;label;labels
  data:
  - env/FluentSpeechCommands/test/test_intent_with_text_00000{00..03}.tar.gz
  batch_size: 4
  num_workers: 0
  metric: Accuracy
eval_freemusicarchive:
  prompt: Classify the music genre (FMA).
  key: text;caption;captions;label;labels
  data:
  - env/FreeMusicArchive/test/fma_small_test_00000{00..07}.tar.gz
  batch_size: 4
  num_workers: 0
  metric: Accuracy
eval_fsd50k:
  prompt: Multi-label classification for FSD50k
  key: text;caption;captions;label;labels
  data:
  - env/FSD50k/test/eval_with_text_0000{00..31}.tar.gz
  batch_size: 4
  num_workers: 0
  metric: mAP
eval_fsdkaggle2018:
  prompt: Multi-label classification for FSDKaggle2018
  key: text;caption;captions;label;labels
  data:
  - env/FSDKaggle2018/test/test_with_text_00000{00..02}.tar.gz
  batch_size: 4
  num_workers: 0
  metric: mAP
eval_gtzan:
  prompt: Classify the music genre (GTZAN).
  key: text;caption;captions;label;labels
  data:
  - env/GTZAN/test/gtzan_fold_9_0000000.tar.gz
  batch_size: 4
  num_workers: 0
  metric: Accuracy
eval_libricount:
  prompt: Count the amount of speakers.
  key: text;caption;captions;label;labels
  data:
  - env/LibriCount/test/libricount_fold04.tar.gz
  batch_size: 4
  num_workers: 0
  metric: Accuracy
eval_librispeech:
  prompt: Transcribe the English speech into text
  key: text;caption;captions;label;labels
  data:
  - env/LibriSpeech/test/test-clean-0000{00..19}.tar.gz
  batch_size: 4
  num_workers: 0
  metric: iWER
eval_nsynth:
  prompt: Classify the music instrument.
  key: text;caption;captions;label;labels
  data:
  - env/NSynth/test/test_00000{0..5}.tar.gz
  batch_size: 4
  num_workers: 0
  metric: Accuracy
eval_speechcommandsv1:
  prompt: Classify the keyword.
  key: text;caption;captions;label;labels
  data:
  - env/SpeechCommandsV1/test/test_renamed_with_text_00000{00..06}.tar.gz
  batch_size: 4
  num_workers: 0
  metric: Accuracy
eval_urbansound8k:
  prompt: Classify the urban sound.
  key: text;caption;captions;label;labels
  data:
  - env/Urbansound8k/test/urbansound_fold10_0000000.tar.gz
  batch_size: 4
  num_workers: 0
  metric: Accuracy
eval_vocalsound:
  prompt: Classify the vocal sound.
  key: text;caption;captions;label;labels
  data:
  - env/VocalSound/test/test_00000{00..04}.tar.gz
  batch_size: 4
  num_workers: 0
  metric: Accuracy
eval_voxceleb1:
  prompt: Are the two speakers the same or different?
  key: text;caption;captions;label;labels
  data:
  - env/VoxCeleb1/test/test_0000{00..18}.tar.gz
  batch_size: 4
  num_workers: 0
  metric: Accuracy
