train_data:
  ASVSpoof2015:
    prompt: Detect if the audio is genuine or a spoof.
    data:
    - ASVSpoof2015/train/asvspoof_train_0000{00..17}.tar.gz
    key: binary_spoof
    repo_id: mispeech/xares_llm_data
num_training_workers: 4
