train_data:
  ESC-50:
    prompt: Classify the environmental sound.
    data:
    - env/ESC-50/train/esc50_fold_{01..04}_0000000.tar.gz
    key: text;caption;captions;label;labels
num_training_workers: 4
