max_steps: 50000
train_data:
  LibriSpeech:
    prompt: Transcribe the English speech into text
    data:
    - LibriSpeech/train/train-clean-100-0000{00..19}.tar.gz
    key: trans
    repo_id: mispeech/xares_llm_data
num_training_workers: 4
