train_data:
  Songdescriber:
    prompt: Generate a caption for the music
    data:
    - env/Songdescriber/train/train_song_describer_00000{00..01}.tar.gz
    key: text;caption;captions;label;labels
num_training_workers: 4
