train_data:
  SpeechCommandsV1:
    prompt: Classify the keyword.
    data:
    - env/SpeechCommandsV1/train/train_renamed_with_text_0000{00..51}.tar.gz
    key: text;caption;captions;label;labels
num_training_workers: 4
