train_data:
  VocalSound:
    prompt: Classify the vocal sound.
    data:
    - env/VocalSound/train/train_with_text_0000{00..02}0.tar.gz
    key: text;caption;captions;label;labels
num_training_workers: 4
