train_data:
  VoxCeleb1:
    prompt: Are the two speakers the same or different?
    data:
    - env/VoxCeleb1/train/train_0000{00..39}.tar.gz
    key: text;caption;captions;label;labels
num_training_workers: 4
